import Wrapper from "../components/Wrapper";
import { ReduxProviders } from "../redux/providers";
import ThemeProviders from "../theme/ThemeProviders";
import "./globals.css";

export const metadata = {
  title: "School LMS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProviders>
          <ThemeProviders>
            <Wrapper>{children}</Wrapper>
          </ThemeProviders>
        </ReduxProviders>
      </body>
    </html>
  );
}
